- app/Auth/Abilities/TastingAbilities.php
- app/Contracts/TastingHandler.php
- app/Database/Repositories/ActivityLogRepository.php
- app/Database/Repositories/ApplicantRepository.php
- app/EnrollmentForm.php
- app/MasterData/Applicant.php
- app/MasterData/ApplicantValidator.php
- app/Tasting/Handler.php
- database/factories/ModelFactory.php
- database/migrations/2016_08_09_072103_create_users_table.php
- database/seeds/CompetitionTableSeeder.php
- database/seeds/TasterTableSeeder.php
- database/seeds/TastingTableSeeder.php
- database/seeds/UserTableSeeder.php
- database/seeds/WineSortTableSeeder.php
@ChristophWurst requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/ChristophWurst/weinstein_server/
> Scrutinizer Auto-Fixes

- tests/Unit/Auth/Abilities/TastingSessionAbilitiesTest.php
> [Task#49] test edit taster permissions

- app/Http/Controllers/WineController.php
- app/Http/routes.php
> [Refactoring] remove dead codes and dead unused routes

- app/Exceptions/ValidationModelMissingException.php
> Fix namespace

- app/Auth/Abilities/WineAbilities.php
- app/Http/Controllers/WineController.php
- app/Providers/AuthServiceProvider.php
- tests/Unit/Auth/Abilities/WineAbilitiesTest.php
> [Task#50] make sure applicants create wines only while enrollment

- app/Contracts/WineHandler.php
- app/Exceptions/WineLockedException.php
- app/Wine/Handler.php
- tests/Unit/Wine/HandlerTest.php
> [Task#48] Do not allow any changes as soon as a nr has been assigned

- app/Http/Controllers/WineApiController.php
- app/client/js/views/errormodalview.js
- app/client/js/views/wineview.js
- resources/views/default.blade.php
> [US#44] show visual feedback if updating a wine fails

- tests/Unit/Validation/WineValidatorFactoryTest.php
> [Refactoring] Test the WineValidatorFactory

- app/Auth/Abilities/WineAbilities.php
- app/Http/Controllers/WineController.php
- app/Providers/AuthServiceProvider.php
- tests/Unit/Auth/Abilities/WineAbilitiesTest.php
* Hide button if user is not a competition admin
* Adjust abilities
* Add unit tests for abilities
> [US#37] Only competition admins may import sosi wines

- .dockerignore
- .travis.yml
- build/docker-images.sh
- deploy/app.docker
- deploy/vhost.conf
- deploy/web.docker
Ref
- https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
- http://tornike.me/notes/laravel-build-and-deployment-on-vps-over-github
- https://medium.com/@andrewmclagan/you-thought-laravel-homestead-was-easy-say-hello-to-docker-2c0639a0501#.29efjuuwp
- https://kyleferg.com/laravel-development-with-docker/#database-with-docker
- https://medium.com/@shakyShane/laravel-docker-part-2-preparing-for-production-9c6a024e9797#.pttijj2w6
- https://medium.com/@andrewmclagan/you-thought-laravel-homestead-was-easy-say-hello-to-docker-2c0639a0501#.bowuakg9p
- https://medium.com/@mrfoh/developing-laravel-applications-with-docker-7324c0a0789a#.j8cuqscyl
> Add docker image support and build them on Travis

- .dockerignore
- deploy/app.docker
Defines a volume at `/var/www/storage` to make sure the directory structure exists and is writable.
> Create a volume for the storage directory

- app/Tasting/Handler.php
Fixes https://tree.taiga.io/project/christophwurst-weinstein/issue/4
> Do not fail hard if the comment is not set

- app/Http/Controllers/TastingNumberController.php
- resources/views/default.blade.php
Fixes https://tree.taiga.io/project/christophwurst-weinstein/issue/64
> Show competition navigation on tasting number pages

- app/Http/Controllers/CompetitionController.php
- app/Http/Controllers/TastingNumberController.php
- app/Http/Controllers/TastingSessionController.php
- app/Providers/AppServiceProvider.php
- app/Wine.php
- resources/views/competition/show.blade.php
Fixes https://tree.taiga.io/project/christophwurst-weinstein/issue/66
> Allow non-kdb wines in second tasting stage (tasting number assignment)

- deploy/app.docker
> Manually install pcre package to fix upstream docker image errors

- app/Contracts/WineHandler.php
- app/Http/Controllers/WineController.php
- app/Http/routes.php
- app/Wine/Handler.php
- resources/views/competition/wines/import-chosen.blade.php
- resources/views/competition/wines/index.blade.php
Reverts https://github.com/ChristophWurst/weinstein_server/pull/19/commits/590407115086ab9dd6437eb819d3df505e1ae1ca
> Bring back chosen import

- app/Auth/Abilities/ApplicantAbilities.php
- app/Http/Controllers/ApplicantController.php
- package-lock.json
- resources/views/settings/applicant/form.blade.php
- resources/views/settings/applicant/index.blade.php
- tests/Unit/Auth/Abilities/ApplicantAbilitiesTest.php
- tests/Unit/Http/Controllers/ApplicantControllerTest.php
Fixes https://github.com/ChristophWurst/weinstein_server/issues/173.
> Add ability for assoc admins to add applicants

- app/Contracts/MasterDataStore.php
- app/Http/Controllers/ApplicantController.php
- app/MasterData/Store.php
- resources/views/settings/applicant/index.blade.php
- tests/Unit/Http/Controllers/ApplicantControllerTest.php
Fixes https://github.com/ChristophWurst/weinstein_server/issues/185.
> Show the generated password of an applicant

- app/Wine/Handler.php
- app/Wine/WineValidator.php
- tests/Unit/Wine/HandlerTest.php
> Fix wine attribute validation of non-updated values

- app/Auth/Abilities/WineAbilities.php
- app/Http/Controllers/WineController.php
- app/Providers/AuthServiceProvider.php
- app/Wine.php
- app/WineExport.php
- database/migrations/2018_10_26_062755_winedetails_association_id.php
- resources/views/competition/tasting/tasting-number/form.blade.php
- resources/views/competition/wines/index.blade.php
- resources/views/competition/wines/show.blade.php
- resources/views/default.blade.php
> Fix applicant and association permissions

- app/Http/Controllers/Auth/LoginController.php
- database/migrations/2018_10_26_134140_add_user_firstlogin.php
- resources/views/account/account.blade.php
- tests/Unit/Http/Controllers/LoginControllerTest.php
Fixes https://github.com/ChristophWurst/weinstein_server/issues/177.
> Show a 'password change' warning on first login

- database/migrations/2019_01_09_201100_cascade_delete_signed_off_wines.php
Fixes https://github.com/ChristophWurst/weinstein_server/issues/255
> Fix cascade deletetion of signed off wines

- app/MasterData/Store.php
- app/Wine/Handler.php
> Fix the default 'chosen' state of excluded wines

- app/Http/routes.php
- resources/views/settings/applicant/index.blade.php
- tests/Integration/Settings/ApplicantsTest.php
Fixes https://github.com/ChristophWurst/weinstein_server/issues/282
> Add applicant quick access / search

- package-lock.json
- package.json
> Drop sass-loader

- package-lock.json
- package.json
Reverts ChristophWurst/weinstein_server#1380
> Revert "Bump jquery from 3.5.1 to 3.6.3"
